travis:
  secure:
    BINSTAR_TOKEN: mjswDFCshlRs87uvSqnFdXw7pdngC01sE1t8QR/evWe/eYJJmHTFD6wN43OQgOtQN/1ygID7QkOJMtkvbbWzqVzJ1ENzG6aiB6khf8lZ7gk1dKtk5I52KGDloCR+HCGYdIVCLO6WRiYHWXODtzWc2FnxSTnBD/FvFGBKFv2yskSoUrexJcmYHVS3IM0CO5Xz1sy75oK8Gqo1mzWHB+mrCgnjrcD29m17Zn6TZVauOUleywANY8wxX989HVULh4C37qwEPMrTrf5GJYFCRyW0Sr+1XdTFNIZgR+pUhDvsQsWX/UMLwLqO3oo7otzqGAZSobrEjG6A2TnlI+EaC8PflaAFYDlkMhj4qXC/4pZu91k9kGvQb/cYwGT696uBJvAnlSUChmUk+7w2nLAKTn7UNeoWMLMxnTYDaIgLhktDGzEAhVvcg0VZy3nqh657ek/cm9bX9IY8IhOxlgYyVF5GfAJoELeGcBu14MqWiq16w59t9s/o20maifICy9A/XlpjfJ99jrIh4TnWI/DUsRUZvFEvw0pch0fHWxF4uBs+IJte1CFHXjac9kNVUvwdTNmQN8rBWmnMkKFEDRKjX8xnZSODuoShD2YkBWmVDVFFq+2nWhVrfKgP68uINQNjPBbueGypBLhTXp/XeOLD31RNSmMGrAm8hA2cWYvTzlAv8mg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
